# Generated by Django 5.1.3 on 2024-11-20 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10, message='Title must be at least 10 characters long.')])),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('tags', models.CharField(choices=[('Politics', 'Politics'), ('Sports', 'Sports'), ('Tech', 'Tech'), ('Lifestyle', 'Lifestyle')], max_length=50)),
                ('category', models.CharField(choices=[('News', 'News'), ('Opinion', 'Opinion'), ('Feature', 'Feature')], max_length=50)),
                ('publish_date', models.DateField()),
                ('terms_agreed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
