# Generated by Django 5.1.3 on 2024-11-21 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_author_name_remove_article_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created_by',
            new_name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('opinion', 'Opinion'), ('feature', 'Feature')], default=1, max_length=50, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='email',
            field=models.EmailField(default='defaultemail@example.com', max_length=254, verbose_name='Author Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Publish Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(choices=[('politics', 'Politics'), ('sports', 'Sports'), ('tech', 'Tech'), ('health', 'Health')], default='politics', max_length=50, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
