# Generated by Django 5.1.3 on 2024-11-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_rejection_count_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Opinion', 'Opinion'), ('Feature', 'Feature')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(choices=[('Politics', 'Politics'), ('Sports', 'Sports'), ('Tech', 'Tech'), ('Health', 'Health')], default='politics', max_length=50, verbose_name='Tags'),
        ),
    ]
